name: K3s-destroy

on:
  push:
    branches:
      - main_
  workflow_dispatch:

env:
  TF_VAR_gcp_project_id: id

jobs:
  destroy-K3S:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create SSH KEYs
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          ls -al ~/.ssh
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform Import
        run: |
          cd terraform
          terraform import google_compute_firewall.k3s-firewall k3s-firewall
          terraform import google_compute_instance.k3s-master projects/airy-coil-393209/zones/us-central1-a/instances/k3s-master
        continue-on-error: true

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
