name: K3s 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_gcp_project_id: id 

jobs:
  deploy-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install K3S-UP
        run: |
          curl -sLS https://get.k3sup.dev | sh
          sudo install k3sup /usr/local/bin/

      - name: Install K3S-VERSION
        run: |
          k3sup version

      - name: Create SSH PUB KEY
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
          ls -al ~/
        env:
          MY_SECRET: ${{ secrets.SSH_PUB_KEY }}

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve
