name: K3s 

on:
  push:
    branches:
      - main_
  workflow_dispatch:

env:
  TF_VAR_gcp_project_id: id 

jobs:
  deploy-k3s:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install K3S-UP
        run: |
          #curl -sLS https://get.k3sup.dev | sh
          wget https://github.com/alexellis/k3sup/releases/download/0.13.10/k3sup
          chmod +x k3sup
          sudo cp k3sup /usr/local/bin/
          pwd
          ls -al

      - name: Install K3S-VERSION
        run: |
          k3sup version

      - name: Create SSH KEYs
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          ls -al ~/.ssh
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Check SSH KEYs
        run: |
          echo "$SSH_PUB_KEY" > /tmp/id_rsa.pub
          echo "$SSH_KEY" > /tmp/id_rsa
          cat /tmp/id_rsa
          cat /tmp/id_rsa.pub
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve
