name: K3s 

on:
  push:
    branches:
      - main_
  workflow_dispatch:

env:
  TF_VAR_gcp_project_id: id 

jobs:
  deploy-k3s:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install K3S-UP
        run: |
          #curl -sLS https://get.k3sup.dev | sh
          wget https://github.com/alexellis/k3sup/releases/download/0.13.10/k3sup
          chmod +x k3sup
          sudo cp k3sup /usr/local/bin/
          pwd
          ls -al

      - name: Install K3S-VERSION
        run: |
          k3sup version

      - name: Create SSH KEYs & CONFIG
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUB_KEY" > /tmp/id_rsa.pub
          echo "$SSH_KEY" > /tmp/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          echo "$SSHCONFIG"  > ~/.ssh/config
          chmod 400 ~/.ssh/config
          ls -al ~/.ssh
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSHCONFIG: ${{ vars.SSHCONFIG }}

      - name: Check SSH KEYs
        run: |
          ls -al /tmp
          cat /tmp/id_rsa
          cat /tmp/id_rsa.pub
          cat ~/.ssh/config

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Get VM IP Address
        id: get-ip
        run: |
          cd terraform
          VM_IP=$(terraform output -raw external_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

      - name: Check connection
        run: |
          sleep 8s
          nc -zv $VM_IP 22
        continue-on-error: true

      - name: K3s bootstrap
        run: |
          k3sup install \
            --ip $VM_IP \
            --context k3s \
            --ssh-key ~/.ssh/id_rsa \
            --user gabriel

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Check K3s
        run: |
          export KUBECONFIG=/home/runner/work/scalabit-/scalabit-/kubeconfig
          kubectl config use-context k3s
          kubectl get node -o wide
          echo "KUBECONFIG=/home/runner/work/scalabit-/scalabit-/kubeconfig" >> $GITHUB_ENV

      - name: Cat kubeconfig
        run: |
          cat  /home/runner/work/scalabit-/scalabit-/kubeconfig

      - name: Deploy Gatekeeper
        run: |
          kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.15/deploy/gatekeeper.yaml
          kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/template.yaml

      - name: Deploy Gatekeeper Constraint
        run: |
          kubectl apply -f manifests/gk-constraint.yaml
