name: K3s 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_gcp_project_id: your-gcp-project-id  # <<< UPDATE THIS
  TF_VAR_gcp_region: us-central1              # <<< UPDATE THIS
  SSH_KEY_NAME: deploy_key

jobs:
  deploy-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create SSH PUB KEY
        run: |
          echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
        env:
          MY_SECRET: ${{ secrets.SSH_PUB_KEY }}

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve
